name: Deploy to EC2

on:
  push:
    branches:
      - main # main 브랜치에 push 될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{secrets.EC2_PUBLIC_IP_ADDRESS}} << 'EOF'
            echo "SSH DONE"
            hostname

            cd ~/backend/PortfolioSpringBoot
            git pull

            ./mvnw clean package -DskipTests

            # tmux 세션이 이미 있으면 제거 (선택)
            tmux kill-session -t portfolio || true
      
            # 새로운 tmux 세션에서 실행
            tmux new-session -d -s portfolio 'CORS_ALLOWED_ORIGINS=https://91b.co.uk JWT_SECRET=wl39-91b java -jar target/portfolio-0.0.1-SNAPSHOT.jar'
          EOF
